### ISSUE TITLE
Provide functionality to ignore web element cache

### ISSUE THREAD

**Issue by mmanski** [Cognifide/bobcat#158]
Sometimes, when WebElement is injected a StaleElementReferenceException can be thrown when f.e. some button will change or dissappear and re-appear again. In order to avoid that, instead of injecting class field, the WebDriver's findElement() method is used at each time. It would be nice to have annotation that can be put on a class field and act similar to the mentioned workround hiding it. 

References: 
http://www.seleniumhq.org/exceptions/stale_element_reference.jsp

https://github.com/Cognifide/bobcat/blob/1.2.0/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/siteadmin/aem61/SiteadminToolbar.java#L177

**Comment by mkrzyzanowski** [comment]
As discussed with @mmanski, WebElements are not being cached unless they are decorated with `@CacheLookup` (they are simply proxies), thus there is no need to introduce an 'ignore cache' functionality.

The problem described above is more about preventing the `StaleElementReferenceException` due to unexpected/unpredictable DOM changes. The new annotation would be something more like the old `@Refreshable` that we had, which is simply a more sophisticated try-catch working around the above problem. Imho, this could be handled with existing functionality, e.g. using `@LoadableCondition` that evaluates staleness check, instead of introducing a bunch of additional code. This sort of functionality could also drive people to spam it left and right, instead of actually controlling the test flow.

@kkarolk @rgrzesk thoughts?
