### ISSUE TITLE
How to automate the complex dropdown in the dialog.

### ISSUE THREAD

**Issue by ShuklaShubh89** [Cognifide/bobcat#206]
As a part of my project, i wnted to automate the complex dropdowns in the aem dialog, as present in the screenshot.
Please suggest how to, or if there already is a way.

![image](https://user-images.githubusercontent.com/9858947/28120975-509328bc-6737-11e7-84d4-fb0eabf35e52.png)

**Comment by DeChrish** [comment]
@ShuklaShubh89 Please share the component with sample tabs. We can try to recreate the problem.

**Comment by mkrzyzanowski** [comment]
Hi @ShuklaShubh89,
have been some time since I've used AEM's ClassicUI but it seems like Tag picker - try using the `AemTags` field: [link](https://github.com/Cognifide/bobcat/blob/a54cf837f0699edf6f607f39f610c500ae2a5c23/bb-aem-classic/src/main/java/com/cognifide/qa/bb/aem/dialog/classic/field/tags/AemTags.java)

If it does not work - you can still use that example for writing your own custom dialog field.
