### ISSUE TITLE
[HELP] Wiki for Implementing custom dialog fields for Multifields

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#210]
Hi @marcinczeczko, 
Currently Wiki page has documentation for  Implementing custom dialog fields (TEXTFIELD). Can you please provide documentation for custom Multi Field? Appreciated.

**Comment by mkrzyzanowski** [comment]
Hi @DeChrish,
what kind of custom Multifield are you trying to implement?
In case of the current TouchUI module you can take a look at two classes that are used to handle this type of field (due to their nature, they are a bit more complex than regular fields):

- [Multifield](https://github.com/Cognifide/bobcat/blob/master/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/pageobjects/touchui/dialogfields/Multifield.java)
- [MultifieldItem](https://github.com/Cognifide/bobcat/blob/master/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/pageobjects/touchui/dialogfields/MultifieldItem.java)

The rules are the same here - your custom classes should implement the `DialogField` interface and should be registered in your module, as described on the Wiki.
Let me know if you have any more questions.

**Comment by DeChrish** [comment]
@mkrzyzanowski Thanks, am working on it.  Sample YAML file will be helpful.  

- Multifield
- MultifieldItem

**Comment by mkrzyzanowski** [comment]
Example YAML can be found on wiki here: https://github.com/Cognifide/bobcat/wiki/Component-configurer#complex-fields
Any custom field will follow the same rules, with the `type` matching its name.
