### ISSUE TITLE
bobcat webdriver 

### ISSUE THREAD

**Issue by reedsexpo** [Cognifide/bobcat#215]
Thanks guys for this awsam framwok,]

started using it for a project but could not use  the code below for selenium file upload ...

.setFileDetector does not show under driver , do you have a wrapper around the orignal driver object ?

how can I get around it ?

Many Thanks

John

driver.setFileDetector(new LocalFileDetector());
driver.get("http://www.fileconvoy.com/");
driver.findElement(By.id("upfile_0")).sendKeys("C:\\Users\\hello\\url.txt");
driver.findElement(By.id("readTermsOfUse")).click();
driver.findElement(By.name("form_upload")).submit();

**Comment by mkrzyzanowski** [comment]
Hi @reedsexpo,

apologies for late reply - yes, we are wrapping the `WebDriver` instance in `ClosingAwareWebDriverWrapper`. The whole process can be seen here in [WebDriverProvider](https://github.com/Cognifide/bobcat/blob/a54cf837f0699edf6f607f39f610c500ae2a5c23/bb-core/src/main/java/com/cognifide/qa/bb/provider/selenium/webdriver/WebDriverProvider.java#L114).

Since the `setFileDetector` method comes from `RemoteWebDriver` you have two options:

1. Implement a [WebDriverModifier](https://github.com/Cognifide/bobcat/blob/a54cf837f0699edf6f607f39f610c500ae2a5c23/bb-core/src/main/java/com/cognifide/qa/bb/provider/selenium/webdriver/modifiers/webdriver/WebDriverModifier.java) that sets the necessary detector. This will affect all the instances you create unless you provide an additional flag/properties.
2. Another method for the `WebDriver` instance that you already have: get the wrapped driver and cast it to `RemoteWebDriver`:

    ```
    RemoteWebDriver wrappedDriver = (RemoteWebDriver) ((EventFiringWebDriver) webDriver).getWrappedDriver();
    wrappedDriver.setFileDetector(YOUR_DETECTOR);
    ```

**Comment by reedsexpo** [comment]
@mkrzyzanowski  thanks Method 2 works for me now :)
