### ISSUE TITLE
Support for AEM 6.3?

### ISSUE THREAD

**Issue by user390181** [Cognifide/bobcat#229]
Is there any planned support for authoring in AEM 6.3?  Current version of bobcat appears to only support up to 6.2.

**Comment by mkrzyzanowski** [comment]
Hi @user390181,

as mentioned now in our README, the current version of the TouchUI module was used for automating AEM 6.3, although it does not cover it fully.

Right now, we are re-thinking our approach to AEM and how to keep up with new releases. So I'd say there are no concrete plans in place ;).

**Comment by prashant-varma** [comment]
My project recently upgraded to 6.4. I have been asked to use Bobcat for automation wrapper. Please let me know what all issues could be expected as i guess its not going to support 6.4

**Comment by mkrzyzanowski** [comment]
@prashant-varma as stated above, there is no concrete plan *yet* ;). We want to address the issue of supporting AEM, though we don't have any concrete dates in place.

As for the type of issues you might encounter - some selectors used in the current version of TouchUI module might not work in latest AEM, wherever the interface has been updated by Adobe. If you have any customizations in AEM, then you might find our Page Objects hard to extend (which is something we would like to address too). Our project teams have been maintaining their own versions of TouchUI modules due to the above - you can follow in their footsteps and get inspired by Bobcat's codebase :wink: .

**Comment by mkrzyzanowski** [comment]
We are working on new version of AEM authoring API that will be primarily focusing on AEM 6.4+. Since we also have active projects using it on AEM 6.3, we will try and address the backward compatibility too.
